const $=s=>document.querySelector(s),app=$("#app");let deferredInstall=null,session=null;
const rules=[["🎂","Mindestalter","Mindestens 14 Jahre."],["⚡","Geschwindigkeit","Ein legaler E-Scooter nach eKFV fährt bauartbedingt höchstens 20 km/h."],["🪪","Führerschein","Kein Führerschein und keine Mofa-Prüfbescheinigung nötig."],["🛡️","Versicherung","Für öffentlichen Verkehr: Betriebserlaubnis und gültige Versicherungsplakette."],["🚲","Wo fahren?","Innerorts auf vorhandenen Radwegen, Radfahrstreifen und Fahrradstraßen; fehlen diese, auf der Fahrbahn."],["🚶","Gehweg","Auf reinen Gehwegen grundsätzlich nicht fahren, außer besondere Freigabe."],["1️⃣","Nur eine Person","Keine zweite Person mitnehmen."],["🚫","Kein Anhänger","Anhängerbetrieb ist verboten."],["↔️","Fahrweise","Nicht freihändig, nicht anhängen, grundsätzlich hintereinander fahren."],["👋","Abbiegen","Blinker nutzen; ohne Blinker rechtzeitig deutlich Handzeichen geben."],["🐢","Rücksicht","Auf gemeinsamen Geh- und Radwegen haben Fußgänger Vorrang."],["📱","Handy","Während der Fahrt nicht in der Hand bedienen."],["🍺","Alkohol","E-Scooter sind Kraftfahrzeuge. Wer fährt, bleibt nüchtern."],["📦","Ladung","Du musst jederzeit sicher lenken und bremsen können. Zwei lose Bierkästen auf dem Trittbrett sind keine clevere Lösung. 😎"]];
const signs=[["yield","Vorfahrt gewähren","Andere zuerst fahren lassen."],["stop","STOP","Vollständig anhalten und Vorfahrt beachten."],["diamond","Vorfahrtstraße","Du befindest dich auf einer Vorfahrtstraße."],["speed","Tempo 30","Nicht schneller als 30 km/h; der E-Scooter selbst bleibt max. 20."],["noentry","Verbot der Einfahrt","Hier nicht einfahren, außer ausdrückliche Freigabe."],["allvehicles","Verbot für Fahrzeuge aller Art","Fahren verboten; schieben ist möglich."],["bike","Radweg","Zulässige Radverkehrsfläche."],["walk","Gehweg","Grundsätzlich nicht mit E-Scooter befahren."],["oneway","Einbahnstraße","Nur in vorgeschriebener Richtung, außer Ausnahmefreigabe."],["roundabout","Kreisverkehr","Fahrtrichtung beachten; beim Ausfahren Richtung anzeigen."],["warning","Gefahrstelle","Tempo anpassen und bremsbereit sein."],["zebra","Fußgängerüberweg","Fußgänger durchlassen."]];
const q=[
["Wo fährst du innerorts, wenn ein Radweg vorhanden ist?",["Auf dem Radweg","Auf dem Gehweg","Nur links auf der Fahrbahn"],0,"Vorhandene Radverkehrsflächen sind die richtige Verkehrsfläche."],
["Wie alt musst du mindestens sein?",["12","14","16"],1,"Mindestalter: 14 Jahre."],
["Darf eine zweite Person mitfahren?",["Ja","Nur bis 10 km/h","Nein"],2,"Personenbeförderung ist verboten."],
["Was bedeutet STOP?",["Nur langsamer werden","Vollständig anhalten und Vorfahrt beachten","Nur bei Verkehr anhalten"],1,"STOP heißt vollständiger Halt."],
["Was gilt ohne Ampel und Vorfahrtsschilder grundsätzlich?",["Rechts vor links","Der Schnellere zuerst","E-Scooter zuerst"],0,"An unbeschilderten Kreuzungen gilt grundsätzlich rechts vor links."],
["Darfst du auf einem reinen Gehweg fahren?",["Ja in Schrittgeschwindigkeit","Nein, grundsätzlich nicht","Nur sonntags"],1,"Ein reiner Gehweg ist grundsätzlich tabu."],
["Welche bauartbedingte Höchstgeschwindigkeit hat ein legaler E-Scooter höchstens?",["20 km/h","25 km/h","30 km/h"],0,"Die eKFV erfasst Fahrzeuge bis höchstens 20 km/h."],
["Keine Blinker: Wie zeigst du das Abbiegen an?",["Klingeln","Deutliches Handzeichen","Kurz bremsen"],1,"Ohne Blinker rechtzeitig Handzeichen geben."],
["Was bedeutet 'Vorfahrt gewähren'?",["Immer vollständig anhalten","Andere zuerst fahren lassen","Du hast Vorfahrt"],1,"Bevorrechtigten Verkehr zuerst fahren lassen."],
["Darfst du freihändig fahren?",["Ja","Nein","Nur unter 10 km/h"],1,"Freihändiges Fahren ist verboten."],
["Was gilt am Zebrastreifen?",["Fußgänger durchlassen","Beschleunigen","Nur Autos müssen warten"],0,"Fußgänger dürfen nicht gefährdet oder behindert werden."],
["Darfst du dich an ein fahrendes Auto anhängen?",["Nein","Ja, wenn langsam","Nur bergauf"],0,"Anhängen an fahrende Fahrzeuge ist verboten."],
["Was braucht der E-Scooter im öffentlichen Straßenverkehr?",["Nur Helm","Betriebserlaubnis und gültige Versicherungsplakette","Pkw-Führerschein"],1,"Für öffentlichen Verkehr gelten Betriebserlaubnis und Versicherung."],
["Gemeinsamer Geh- und Radweg: Was gilt?",["Fußgänger haben Vorrang","E-Scooter haben Vorrang","Immer klingeln und durch"],0,"Fußgänger haben Vorrang."],
["Rote Ampel?",["Weiter wenn frei","Anhalten","Nur langsamer"],1,"Rot heißt Halt."],
["Was prüfst du vor der Fahrt?",["Bremsen, Reifen, Licht und Akku","Nur Akku","Nur Klingel"],0,"Ein kurzer Sicherheitscheck gehört dazu."],
["Unübersichtliche Stelle?",["Schnell durch","Tempo reduzieren und bremsbereit sein","Mittig beschleunigen"],1,"Nur so schnell fahren, dass du reagieren kannst."],
["Darfst du einen Anhänger ziehen?",["Ja","Nur leer","Nein"],2,"Anhängerbetrieb ist verboten."],
["Wie fährst du mit anderen E-Scootern?",["Nebeneinander","Einzeln hintereinander","Zu dritt nebeneinander"],1,"Grundsätzlich einzeln hintereinander."],
["Nasse Fahrbahn?",["Mehr Abstand und langsamer","Wie trocken","Stärker beschleunigen"],0,"Nässe reduziert Haftung und verlängert den Bremsweg."],
["Schnelleres Fahrrad will überholen?",["Blockieren","Überholen ermöglichen","Beschleunigen"],1,"Schnellerer Radverkehr soll überholen können."],
["Handy während der Fahrt in der Hand bedienen?",["Ja kurz","Nein","Nur an Kreuzungen"],1,"Das Handy gehört während der Fahrt nicht in die Hand."],
["Wie viel Abstand?",["So viel, dass du sicher anhalten kannst","10 cm","Egal"],0,"Du brauchst Reaktions- und Bremsweg."],
["Von rechts kommt ein Auto an unbeschilderter Kreuzung.",["Du hast Vorfahrt","Das Auto von rechts","Wer hupt"],1,"Rechts vor links."],
["Warum ist ein Helm sinnvoll?",["Kann Kopfverletzungen reduzieren","Macht schneller","Ersetzt Licht"],0,"Ein Helm kann Kopfverletzungen reduzieren."],
["Zwei lose Bierkästen auf dem Trittbrett beeinträchtigen die sichere Führung. Erlaubt?",["Ja, immer","Nein","Nur bergab"],1,"Du musst sicher lenken und bremsen können. Sorry. 🍺🍺"],
["Gefahr bei parkenden Autos?",["Plötzlich öffnende Türen","Nur deren Farbe","Keine"],0,"Mit plötzlich öffnenden Türen rechnen."],
["Musik so laut, dass du Martinshorn nicht hörst?",["Ja","Nein","Nur auf Radwegen"],1,"Warnsignale müssen wahrnehmbar bleiben."],
["Kinder oder Hunde nahe am Weg?",["Tempo reduzieren und bremsbereit sein","Vollgas","Dicht vorbei"],0,"Mit unvorhersehbaren Bewegungen rechnen."],
["Bremse defekt?",["Nicht weiterfahren","Langsam weiterfahren","Nur klingeln"],0,"Bei sicherheitsrelevantem Defekt Fahrt beenden."]];
const store={get(){try{return JSON.parse(localStorage.getItem("eroller_history")||"[]")}catch{return[]}},add(x){const a=this.get();a.unshift(x);localStorage.setItem("eroller_history",JSON.stringify(a.slice(0,20)))},clear(){localStorage.removeItem("eroller_history")}};
function signMarkup(t){if(t==="yield")return'<div class="sign yield"></div>';if(t==="stop")return'<div class="sign stop">STOP</div>';if(t==="diamond")return'<div class="sign diamond"></div>';if(t==="speed")return'<div class="sign circle">30</div>';if(t==="noentry")return'<div class="sign circle noentry"></div>';if(t==="allvehicles")return'<div class="sign circle"></div>';if(t==="bike")return'<div class="sign circle blue">🚲</div>';if(t==="walk")return'<div class="sign circle blue">🚶</div>';if(t==="oneway")return'<div class="sign oneway"></div>';if(t==="roundabout")return'<div class="sign circle blue">↻</div>';if(t==="warning")return'<div class="sign warning"><span>!</span></div>';return'<div class="sign oneway">🚶</div>'}
function setActive(r){document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.go===r))}
function go(r){history.replaceState(null,'',`#${r}`);render(r)}document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});window.addEventListener('hashchange',()=>render(location.hash.slice(1)||'home'));
function home(){const h=store.get();app.innerHTML=`<section class="hero"><div class="tag">DER DEAL STEHT 😎</div><h1>E-Roller-<br>Fahrschule</h1><p>Erst Schilder und Regeln lernen, dann üben – und zum Schluss die Abschlussprüfung bestehen.</p><button class="btn" data-go="rules">Lernen starten</button></section><section class="grid"><div class="card action-card" data-go="signs"><span class="emoji">🚦</span><div><h3>Verkehrsschilder</h3><p>Die wichtigsten Schilder kurz erklärt.</p></div></div><div class="card action-card" data-go="rules"><span class="emoji">📘</span><div><h3>Einfache Regeln</h3><p>Radweg, Fahrbahn, Vorfahrt, Abbiegen und Sicherheit.</p></div></div><div class="card action-card" data-go="practice"><span class="emoji">🧠</span><div><h3>Übungsmodus</h3><p>10 zufällige Fragen mit Erklärung.</p></div></div><div class="card action-card" data-go="exam"><span class="emoji">🏁</span><div><h3>Abschlussprüfung</h3><p>20 Fragen. Ab 17 richtigen bestanden.</p></div></div></section><section class="card" style="margin-top:16px"><div class="section-title"><div><h2 style="margin:0">Letzte Ergebnisse</h2><p>Nur auf diesem Gerät gespeichert.</p></div>${h.length?'<button class="btn ghost" id="clearHistory">Löschen</button>':''}</div>${h.length?`<div class="history">${h.slice(0,6).map(x=>`<div class="history-row"><span>${x.type} · ${x.date}</span><strong>${x.score}/${x.total} ${x.passed?'✅':'❌'}</strong></div>`).join('')}</div>`:'<p class="muted">Noch keine Prüfung gefahren. 😄</p>'}</section><p class="muted" style="font-size:12px">Private Lern-App, keine amtliche Fahrschulprüfung. Regelstand: August 2026.</p>`;$('#clearHistory')?.addEventListener('click',()=>{store.clear();home()})}
function renderSigns(){app.innerHTML=`<div class="section-title"><div><h1>Verkehrsschilder</h1><p>Die wichtigsten für unseren Test.</p></div><button class="btn" data-go="practice">Danach üben →</button></div><div class="sign-grid">${signs.map(s=>`<article class="card sign-card"><div class="sign-art">${signMarkup(s[0])}</div><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('')}</div>`}
function renderRules(){app.innerHTML=`<div class="section-title"><div><h1>Einfache Regeln</h1><p>Überschaubar, aber wichtig.</p></div><button class="btn" data-go="practice">Ich hab's verstanden →</button></div><div class="rule-list">${rules.map(r=>`<article class="card rule"><div class="icon">${r[0]}</div><div><h3>${r[1]}</h3><p>${r[2]}</p></div></article>`).join('')}</div><div class="notice" style="margin-top:14px"><strong>Merksatz:</strong> Unsicher? Tempo raus, bremsbereit sein und nötigenfalls anhalten.</div>`}
function shuffled(a){return[...a].sort(()=>Math.random()-.5)}function startQuiz(mode){session={mode,items:shuffled(q).slice(0,mode==='exam'?20:10),idx:0,answers:[]};renderQuiz()}
function renderQuiz(){const it=session.items[session.idx],ans=session.answers[session.idx],exam=session.mode==='exam';app.innerHTML=`<div class="quiz-shell"><div class="section-title"><div><h1>${exam?'Abschlussprüfung':'Übungsmodus'}</h1><p>${exam?'20 Fragen · bestanden ab 17 richtig':'10 zufällige Fragen · mit Erklärung'}</p></div></div><div class="qmeta"><span>Frage ${session.idx+1} von ${session.items.length}</span><span>${exam?'Prüfung':'Training'}</span></div><div class="progressbar"><div style="width:${(session.idx+1)/session.items.length*100}%"></div></div><section class="card"><div class="question">${it[0]}</div><div class="answers">${it[1].map((a,i)=>{let c='answer';if(ans!=null){if(i===it[2])c+=' correct';if(i===ans&&ans!==it[2])c+=' wrong'}return`<button class="${c}" data-answer="${i}" ${ans!=null?'disabled':''}><strong>${'ABC'[i]}.</strong> ${a}</button>`}).join('')}</div>${ans!=null?`<div class="feedback">${ans===it[2]?'✅ Richtig.':'❌ Nicht ganz.'} ${it[3]}</div>`:''}<div class="quiz-actions"><button class="btn ghost" data-go="home">Abbrechen</button>${ans!=null?`<button class="btn" id="nextQ">${session.idx===session.items.length-1?'Auswerten':'Nächste Frage →'}</button>`:''}</div></section></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{session.answers[session.idx]=Number(b.dataset.answer);renderQuiz()}));$('#nextQ')?.addEventListener('click',()=>session.idx===session.items.length-1?finishQuiz():(session.idx++,renderQuiz()))}
function finishQuiz(){const score=session.items.reduce((s,it,i)=>s+(session.answers[i]===it[2]?1:0),0),total=session.items.length,passed=session.mode==='exam'?score>=17:score>=8;store.add({type:session.mode==='exam'?'Prüfung':'Übung',score,total,passed,date:new Date().toLocaleDateString('de-DE')});app.innerHTML=`<div class="quiz-shell"><section class="card scorebox"><p class="muted">${session.mode==='exam'?'ABSCHLUSSPRÜFUNG':'ÜBUNG'}</p><div class="score ${passed?'pass':'fail'}">${score}/${total}</div><h1>${passed?(session.mode==='exam'?'Bestanden! 🏆':'Sauber! ✅'):'Noch einmal ran. 😎'}</h1><p class="muted">${session.mode==='exam'?(passed?'Der Deal ist erfüllt.':'Für die Prüfung brauchen wir 17 richtige Antworten.'):'Ziel im Training: mindestens 8 von 10.'}</p><button class="btn" data-go="home">Zur Startseite</button></section></div>`;session=null}
function render(r){r=['home','signs','rules','practice','exam'].includes(r)?r:'home';setActive(r);if(r==='home')home();else if(r==='signs')renderSigns();else if(r==='rules')renderRules();else if(r==='practice')startQuiz('practice');else{app.innerHTML=`<div class="quiz-shell"><section class="card scorebox"><div style="font-size:54px">🏁</div><h1>Abschlussprüfung</h1><p class="muted">20 zufällige Fragen.<br><strong style="color:#fff">Bestanden ab 17 von 20.</strong></p><div class="notice" style="text-align:left;margin:18px 0"><strong>Prüferehre:</strong> Keine Hilfe und kein Papa-Google. 😄</div><button class="btn" id="startExam">Prüfung starten</button></section></div>`;$('#startExam').addEventListener('click',()=>startQuiz('exam'))}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden');$('#installHint').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render(location.hash.slice(1)||'home');