// V2.4 – größerer Fragenpool, Prüfungsreife, unbegrenzte Historie, Update-Knopf
(function(){
const extra=[
["Du fährst aus einer Grundstücksausfahrt auf die Straße. Wer hat Vorrang?",["Ich, wenn ich zuerst an der Kante bin","Der Verkehr auf Straße und Geh-/Radweg","Nur Autos"],1,"Beim Ausfahren aus Grundstücken ist besondere Vorsicht nötig; der fließende Verkehr hat Vorrang."],
["Vor einer Kurve liegt Splitt. Was ist richtig?",["Vorher Tempo reduzieren und möglichst ruhig lenken","In der Kurve stark bremsen","Beschleunigen, damit die Räder stabiler werden"],0,"Auf losem Untergrund sinkt die Haftung."],
["Ein Auto setzt rückwärts aus einer Parklücke. Du bist unsicher, ob man dich sieht.",["Weiter, ich habe Vorrang","Tempo raus, bremsbereit sein und Blickkontakt suchen","Dicht hinter dem Auto vorbeifahren"],1,"Rechne damit, übersehen zu werden."],
["Warum ist seitlicher Abstand zu parkenden Autos wichtig?",["Wegen plötzlich öffnender Türen","Nur wegen Außenspiegeln","Damit der Akku kühler bleibt"],0,"Öffnende Türen sind eine typische Gefahr."],
["Du willst eine Pfütze umfahren. Was prüfst du zuerst?",["Ob hinter/neben dir Verkehr ist","Nur wie tief die Pfütze ist","Nichts, sofort ausweichen"],0,"Vor einem Ausweichmanöver muss der übrige Verkehr beachtet werden."],
["Ein Ball rollt zwischen parkenden Autos auf die Fahrbahn. Was erwartest du?",["Möglicherweise läuft ein Kind hinterher","Nichts, Bälle haben keine Vorfahrt","Nur einen Hund"],0,"Bei einem Ball ist mit Kindern zu rechnen: sofort bremsbereit sein."],
["Du wirst von tief stehender Sonne geblendet. Was tust du?",["Tempo reduzieren und nur so schnell fahren, wie du sicher sehen kannst","Augen kurz schließen","Schneller fahren, damit du schneller aus der Sonne bist"],0,"Sichtweite bestimmt die sichere Geschwindigkeit."],
["Eine Baustelle verengt den Radweg stark. Was ist wichtig?",["Langsam und mit ausreichendem Abstand passieren; nötigenfalls warten","Mit 20 km/h durch die Lücke","Auf den Gehweg ausweichen und klingeln"],0,"Engstellen erfordern besondere Rücksicht."],
["Vor dir fährt jemand unsicher Schlangenlinien mit dem Fahrrad. Wie reagierst du?",["Abstand vergrößern und nicht riskant überholen","Dicht auffahren und klingeln","Rechts vorbeiquetschen"],0,"Unsichere Verkehrsteilnehmer brauchen zusätzlichen Sicherheitsraum."],
["Du bemerkst während der Fahrt einen weichen Vorderreifen. Was ist sinnvoll?",["Sicher anhalten und Zustand prüfen","Bis zum Ziel schneller fahren","Mehr Gewicht auf den Lenker geben"],0,"Ein Reifendefekt kann Lenkung und Bremsverhalten verschlechtern."],
["Warum solltest du vor einer Kreuzung nicht neben einem Lkw stehen bleiben?",["Du kannst im toten Winkel verschwinden","Weil Lkw immer rückwärts fahren","Weil E-Roller dort verboten sind"],0,"Große Fahrzeuge haben erhebliche tote Winkel."],
["Ein Lkw neben dir blinkt rechts. Was ist besonders gefährlich?",["Er könnte beim Abbiegen deinen Weg kreuzen und dich übersehen","Sein Blinker ist zu hell","Er fährt automatisch geradeaus"],0,"Nicht rechts neben einem rechtsabbiegenden Lkw bleiben."],
["Du fährst über Schienen, die deine Fahrtrichtung spitz kreuzen. Wie verringerst du Sturzgefahr?",["Möglichst in größerem Winkel und ohne hektisches Lenken queren","Parallel auf der Schiene fahren","Auf der Schiene bremsen"],0,"Kleine Räder können sich in Schienen verkanten."],
["Warum sind kleine E-Roller-Räder auf Schlaglöchern kritisch?",["Sie können leichter hängen bleiben und den Fahrer aus dem Gleichgewicht bringen","Sie machen den Akku leer","Sie erhöhen automatisch die Geschwindigkeit"],0,"Kleine Räder reagieren empfindlicher auf Unebenheiten."],
["Du fährst bergab. Was verändert sich?",["Geschwindigkeit und Bremsweg können zunehmen","Der Bremsweg wird immer kürzer","Die Vorfahrtregeln gelten nicht"],0,"Gefälle kann den Anhalteweg verlängern."],
["Wann ist Klingeln sinnvoll?",["Als Warnzeichen, wenn es erforderlich ist – nicht als Ersatz für Rücksicht","Immer, um Vorfahrt zu bekommen","Dauerhaft auf jedem Radweg"],0,"Klingeln verschafft keine Vorfahrt."],
["Ein Fußgänger trägt Kopfhörer und läuft nahe am Radweg. Was tust du?",["Mit möglicher Unaufmerksamkeit rechnen und Abstand halten","Dicht vorbeifahren","Nur beschleunigen"],0,"Rechne damit, dass Warnsignale nicht wahrgenommen werden."],
["Du möchtest während der Fahrt eine Nachricht lesen. Was ist richtig?",["Sicher anhalten und erst dann das Handy benutzen","Kurz mit einer Hand lesen","Nur bergab lesen"],0,"Handy nicht während der Fahrt in der Hand bedienen."],
["Warum ist Fahren mit nur einer Hand problematisch, wenn du gleichzeitig etwas Schweres trägst?",["Lenkung und Bremsbereitschaft können beeinträchtigt werden","Der Roller wird dadurch schneller","Es spart Akku"],0,"Du musst das Fahrzeug jederzeit sicher beherrschen."],
["Eine Person möchte hinten auf deinem E-Roller mitfahren. Was gilt?",["Nicht erlaubt – E-Roller sind für eine Person","Erlaubt bis 10 km/h","Erlaubt mit Helm"],0,"Personenbeförderung ist verboten."],
["Du kommst an eine rote Ampel, daneben ist der Gehweg frei. Darfst du über den Gehweg ausweichen?",["Nein","Ja, wenn niemand läuft","Nur wenn du klingelst"],0,"Rot wird nicht durch Ausweichen über den Gehweg umgangen."],
["Du bist müde und kannst dich schlecht konzentrieren. Was ist die beste Entscheidung?",["Fahrt verschieben oder anderes Verkehrsmittel nutzen","Schneller fahren","Musik lauter machen"],0,"Aufmerksamkeit ist für sicheres Fahren entscheidend."],
["Warum sollte man nach starkem Regen besonders auf Fahrbahnmarkierungen achten?",["Sie können rutschiger sein","Sie werden magnetisch","Sie bremsen automatisch"],0,"Nasse Markierungen können weniger Haftung bieten."],
["Ein Hund läuft an langer Leine quer über den Weg. Was tust du?",["Tempo deutlich reduzieren und nötigenfalls anhalten","Zwischen Hund und Halter durchfahren","Klingeln und beschleunigen"],0,"Leinen können eine kaum sichtbare Barriere bilden."],
["Du näherst dich einer Schule zur Unterrichtsendezeit. Womit musst du rechnen?",["Mit plötzlich auf die Fahrbahn tretenden Kindern","Mit völlig freier Fahrbahn","Mit aufgehobenen Verkehrsregeln"],0,"Kinder können sich unvorhersehbar verhalten."],
["Du siehst eine Person mit Blindenstock am Fahrbahnrand. Was gilt?",["Besonders vorsichtig sein und nötigenfalls warten","Klingeln und dicht vorbeifahren","Sie muss immer auf dich warten"],0,"Besonders schutzbedürftige Personen erfordern erhöhte Rücksicht."],
["Was ist beim Fahren über nasses Kopfsteinpflaster sinnvoll?",["Tempo reduzieren und abrupte Lenk-/Bremsmanöver vermeiden","Stark beschleunigen","Nur Vorderbremse ruckartig ziehen"],0,"Unebene nasse Oberflächen können sehr rutschig sein."],
["Du siehst an einer Kreuzung zwar Grün, aber die Kreuzung ist durch Autos blockiert. Was tust du?",["Nicht einfahren, wenn du die Kreuzung nicht räumen kannst","Trotzdem hineinfahren","Auf dem Gehweg vorbeifahren"],0,"Auch bei Grün darf eine Kreuzung nicht unnötig blockiert werden."],
["Vor dir hält ein Auto am Zebrastreifen. Was vermutest du?",["Es könnten Fußgänger queren – nicht einfach vorbeifahren","Das Auto ist kaputt","Ich darf rechts schnell vorbei"],0,"Ein haltendes Fahrzeug kann die Sicht auf Fußgänger verdecken."],
["Warum ist ein Schulterblick vor einem Spur-/Richtungswechsel wichtig?",["Um Verkehr im seitlichen/toten Bereich zu erkennen","Um den Akku zu prüfen","Nur aus Höflichkeit"],0,"Spiegel oder kurzer Blick nach vorn erfassen nicht alle Bereiche."],
["Du musst plötzlich stark bremsen. Welche Fahrweise vorher hätte das Risiko reduziert?",["Ausreichender Abstand und angepasste Geschwindigkeit","Dichtes Auffahren","Freihändiges Fahren"],0,"Sicherheitsreserven verhindern viele Notbremsungen."],
["Auf dem Radweg steht ein Lieferwagen. Darfst du ohne Prüfung sofort auf die Fahrbahn ziehen?",["Nein, erst rückwärtigen/seitlichen Verkehr prüfen und sicher wechseln","Ja, immer","Nur wenn du dabei klingelst"],0,"Ein Hindernis rechtfertigt keinen unkontrollierten Fahrbahnwechsel."],
["Was ist bei Frost besonders kritisch?",["Unsichtbare Glätte, besonders auf Brücken und schattigen Stellen","Nur ein leerer Akku","Dass Verkehrszeichen einfrieren und ungültig werden"],0,"Glatteis kann schwer erkennbar sein."],
["Warum sollte Ladung nicht am Lenker baumeln?",["Sie kann Lenkbewegungen beeinflussen und sich verfangen","Sie verbessert die Balance","Sie verkürzt den Bremsweg"],0,"Lenkung muss frei und kontrollierbar bleiben."],
["Du hast Vorfahrt, aber ein Kind fährt ohne zu schauen aus einer Einfahrt. Was tust du?",["Bremsen und Unfall verhindern","Weiterfahren, weil du Recht hast","Nur klingeln"],0,"Gefahrenabwehr geht vor dem Bestehen auf Vorfahrt."],
["Wann solltest du besonders großen Abstand zum Vordermann halten?",["Bei Nässe, schlechter Sicht oder unsicherem Verkehr","Nur bei Sonnenschein","Nie bei E-Rollern"],0,"Schlechte Bedingungen verlangen mehr Reserve."],
["Was kann bei starkem Seitenwind problematisch sein?",["Der Roller kann seitlich versetzt werden; Tempo und Abstand anpassen","Der Akku lädt sich auf","Bremsen funktionieren nicht mehr grundsätzlich"],0,"Leichte Fahrzeuge reagieren auf Seitenwind."],
["Ein entgegenkommendes Auto blendet dich nachts. Was ist sinnvoll?",["Geschwindigkeit reduzieren und Blick eher zum rechten Fahrbahnrand orientieren","Direkt in die Scheinwerfer schauen","Beschleunigen"],0,"Blendung verringert deine nutzbare Sichtweite."],
["Du kennst eine Strecke sehr gut. Darfst du deshalb bei schlechter Sicht schneller fahren?",["Nein, Geschwindigkeit muss trotzdem zur aktuellen Sicht passen","Ja","Nur mit Helm"],0,"Ortskenntnis ersetzt keine ausreichende Sicht."],
["Was bedeutet defensive Fahrweise?",["Fehler anderer einkalkulieren und Sicherheitsreserven lassen","Immer auf die eigene Vorfahrt bestehen","Grundsätzlich extrem langsam fahren"],0,"Defensiv heißt vorausschauend und mit Reserven fahren."]
];
if(typeof q!=='undefined'&&!q.some(x=>x[4]?.poolV24))extra.forEach(x=>{x[4]={poolV24:true};q.push(x)});
// Lokale Historie nicht mehr künstlich auf 20 Einträge begrenzen.
if(typeof store!=='undefined')store.add=function(x){const a=this.get();a.unshift(x);localStorage.setItem('eroller_history',JSON.stringify(a.slice(0,500)))};
const READY='eroller_readiness_v24';
function readiness(){try{return JSON.parse(localStorage.getItem(READY)||'{"practice":[],"exams":[]}')}catch{return{practice:[],exams:[]}}}
function saveReadiness(mode,score,total){const r=readiness(),k=mode==='exam'?'exams':'practice';r[k].unshift({score,total,pct:Math.round(score/total*100),at:Date.now()});r[k]=r[k].slice(0,50);localStorage.setItem(READY,JSON.stringify(r))}
function readyState(){const r=readiness(),p=r.practice.slice(0,3),e=r.exams.slice(0,2);const pAvg=p.length?Math.round(p.reduce((s,x)=>s+x.pct,0)/p.length):0;const ready=p.length>=3&&pAvg>=85;return{ready,pAvg,pCount:p.length,eCount:e.length}}
const prevFinish=window.finishQuiz;
window.finishQuiz=function(){if(session){const score=session.items.reduce((s,it,i)=>s+(session.answers[i]===it[2]?1:0),0);saveReadiness(session.mode,score,session.items.length)}return prevFinish()};
const prevHome=window.home;
window.home=function(){prevHome();setTimeout(()=>{
 const host=document.querySelector('.mh')||document.getElementById('app');if(!host)return;
 if(!document.getElementById('gudeUpdate')){const b=document.createElement('button');b.id='gudeUpdate';b.className='gude-update';b.textContent='Gude du Opfer 😎 – App aktualisieren';b.onclick=async()=>{b.textContent='Wird frisch gemacht…';try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}const ks=await caches.keys();await Promise.all(ks.map(k=>caches.delete(k)))}catch(e){}location.replace(location.pathname+'?fresh='+Date.now()+'#home')};host.prepend(b)}
 const s=readyState();if(!document.getElementById('readinessBox')){const d=document.createElement('div');d.id='readinessBox';d.className='readiness-box';d.innerHTML=`<strong>🎓 Prüfungsreife: ${s.ready?'JA ✅':'NOCH NICHT 😈'}</strong><span>${s.pCount<3?`Erst ${s.pCount}/3 Wertungsübungen absolviert.`:`Ø der letzten 3 Übungen: ${s.pAvg}%. ${s.ready?'Du darfst dich blamieren.':'Ziel: mindestens 85%.'}`}</span>`;const target=document.querySelector('.mh-stats')||host.children[1];target?.insertAdjacentElement('afterend',d)}}
 },0)};
const prevStart=window.startQuiz;
window.startQuiz=function(mode){if(mode==='exam'){const s=readyState();if(!s.ready){if(!confirm(`Prüfungsreife noch nicht erreicht.\n\nBenötigt: 3 Übungen mit Ø mindestens 85 %.\nAktuell: ${s.pCount}/3 Übungen, Ø ${s.pAvg} %.\n\nTrotzdem zur Prüfung antreten?`))return}}
 if(mode==='exam'){const allHard=q.filter(x=>x[4]?.hardV23||x[4]?.poolV24),signs=q.filter(x=>x[4]?.generatedSignV23),special=q.filter(x=>x[4]?.bollerSpecial),base=q.filter(x=>!x[4]);session={mode:'exam',items:[...shuffled(allHard).slice(0,14),...shuffled(signs).slice(0,3),...shuffled(base).slice(0,2),...shuffled(special).slice(0,1)].sort(()=>Math.random()-.5),idx:0,answers:[]};return window.renderQuiz()}
 return prevStart(mode)};
const css=document.createElement('style');css.textContent=`.gude-update{display:block;width:min(620px,94%);margin:8px auto 16px;padding:14px 18px;border:2px solid #ffbf19;border-radius:16px;background:#ffbf19;color:#090909;font-weight:1000;font-size:16px;cursor:pointer;animation:gudeFly .65s cubic-bezier(.2,.9,.25,1.25)}@keyframes gudeFly{from{transform:translateX(-120vw) rotate(-5deg)}to{transform:translateX(0) rotate(0)}}.readiness-box{width:min(900px,94%);box-sizing:border-box;margin:14px auto;padding:15px 18px;border:1px solid #5d4920;border-radius:16px;background:#111;color:#fff;display:flex;gap:8px;flex-direction:column}.readiness-box strong{color:#ffbf19;font-size:18px}.readiness-box span{color:#bbb}`;document.head.appendChild(css);
})();