// V2.5 – visuelle Verkehrssituationen: verstehen statt auswendig lernen
(function(){
const visual=[
["Du bist der E-Roller unten. Wer fährt zuerst?",["Ich mit dem E-Roller","Das Auto von rechts","Wer zuerst Gas gibt"],1,"Ohne Schilder gilt rechts vor links.",{visualV25:true,scene:'rightcar'}],
["Du willst mit dem E-Roller links abbiegen. Was ist die richtige Reihenfolge?",["Handzeichen, Verkehr beobachten/Schulterblick, sicher einordnen und abbiegen","Einfach links ziehen","Erst in der Kreuzung Handzeichen geben"],0,"Vor dem Abbiegen rechtzeitig anzeigen, Verkehr beobachten und nur sicher abbiegen.",{visualV25:true,scene:'leftturn'}],
["Der Lkw neben dir blinkt rechts. Wo ist für dich die größte Gefahr?",["Rechts neben dem Lkw weiterzufahren","Hinter dem Lkw mit Abstand zu bleiben","Vor der Kreuzung zu warten"],0,"Neben einem rechtsabbiegenden Lkw kannst du im toten Winkel verschwinden.",{visualV25:true,scene:'truck'}],
["Das Auto hält vor dem Zebrastreifen. Was machst du?",["Am Auto vorbeifahren","Tempo reduzieren und mit querenden Fußgängern rechnen","Klingeln und weiter"],1,"Das Auto kann dir die Sicht auf Fußgänger verdecken.",{visualV25:true,scene:'zebra'}],
["Der Radweg endet vor dir. Was ist jetzt richtig?",["Sofort auf die Fahrbahn ziehen","Verkehr prüfen, Tempo anpassen und sicher einordnen","Auf dem Gehweg weiterfahren"],1,"Beim Wechsel auf die Fahrbahn musst du den übrigen Verkehr beachten.",{visualV25:true,scene:'bikeend'}],
["Du hast Grün, aber hinter der Kreuzung ist alles voll. Was tust du?",["In die Kreuzung fahren und warten","Vor der Kreuzung warten, bis du sie räumen kannst","Über den Gehweg fahren"],1,"Auch bei Grün darfst du eine Kreuzung nicht blockieren.",{visualV25:true,scene:'blocked'}],
["Ein Ball rollt zwischen den parkenden Autos hervor. Was ist deine erste Reaktion?",["Sofort bremsbereit werden und Tempo deutlich reduzieren","Weiterfahren – es ist nur ein Ball","Nach links ausweichen ohne zu schauen"],0,"Hinter einem Ball kann unmittelbar ein Kind folgen.",{visualV25:true,scene:'ball'}],
["Du fährst auf nasser Straße auf eine Kurve zu. Wo solltest du hauptsächlich Geschwindigkeit abbauen?",["Vor der Kurve","Mitten in der Kurve","Erst nach der Kurve"],0,"Auf rutschigem Untergrund möglichst vor der Kurve bremsen und in der Kurve ruhig fahren.",{visualV25:true,scene:'wetcurve'}],
["Du bist der E-Roller unten. Das gelbe Auto kommt von rechts, das blaue von links. Keine Schilder. Was gilt?",["Ich fahre zuerst","Ich muss das gelbe Auto von rechts durchlassen","Das blaue Auto von links fährt immer zuerst"],1,"Für dich kommt das gelbe Auto von rechts und hat Vorrang.",{visualV25:true,scene:'cross3'}],
["Du stehst rechts neben dem Lkw an der roten Ampel. Was ist die sicherste Position?",["Direkt neben der Fahrerkabine bleiben","Hinter dem Lkw mit Abstand bleiben","Noch weiter rechts vorbeifahren"],1,"Halte dich aus dem toten Winkel eines abbiegenden Lkw heraus.",{visualV25:true,scene:'truckstop'}],
["Vor dir ist eine Baustellen-Engstelle und Gegenverkehr kommt. Was ist sinnvoll?",["Tempo raus und nötigenfalls warten","Mit 20 km/h durchdrücken","Auf den Gehweg ausweichen"],0,"Engstellen verlangen Übersicht, Abstand und nötigenfalls Warten.",{visualV25:true,scene:'narrow'}],
["Der Hund läuft an einer langen Leine quer über deinen Weg. Was ist die Gefahr?",["Die Leine kann deinen Fahrweg blockieren","Nur der Hund selbst","Keine – E-Roller fahren darunter durch"],0,"Eine dünne Leine ist schlecht sichtbar und kann eine gefährliche Barriere bilden.",{visualV25:true,scene:'dog'}]
];
if(typeof q!=='undefined'&&!q.some(x=>x[4]?.visualV25))visual.forEach(x=>q.push(x));
function sceneSvg(t){const common=`<svg viewBox="0 0 600 330" role="img" aria-label="Verkehrssituation" xmlns="http://www.w3.org/2000/svg"><rect width="600" height="330" rx="24" fill="#252525"/><g stroke="#ddd" stroke-width="4" fill="none">`;
const road=`<path d="M0 165H600M300 0V330"/><path stroke-dasharray="18 16" d="M0 145H600M280 0V330"/></g>`;
const scooter=(x,y,r=0)=>`<g transform="translate(${x} ${y}) rotate(${r})"><circle cx="-20" cy="18" r="12" fill="#111" stroke="#ffbf19" stroke-width="5"/><circle cx="25" cy="18" r="12" fill="#111" stroke="#ffbf19" stroke-width="5"/><path d="M-20 5h45L15-38M15-38h20" stroke="#ffbf19" stroke-width="7" fill="none"/><circle cx="8" cy="-62" r="12" fill="#fff"/><path d="M8-50v38" stroke="#fff" stroke-width="8"/></g>`;
const car=(x,y,c,r=0)=>`<g transform="translate(${x} ${y}) rotate(${r})"><rect x="-42" y="-24" width="84" height="48" rx="14" fill="${c}" stroke="#fff" stroke-width="3"/><circle cx="-24" cy="26" r="7"/><circle cx="24" cy="26" r="7"/></g>`;
const end=`</svg>`;
if(t==='rightcar')return common+road+scooter(300,275)+car(490,165,'#f4c430',90)+end;
if(t==='leftturn')return common+road+scooter(300,275)+`<path d="M300 235Q300 165 215 165" stroke="#ffbf19" stroke-width="12" fill="none" marker-end="url(#a)"/></g>`+end;
if(t==='truck'||t==='truckstop')return common+road+`<g transform="translate(330 130)"><rect x="-65" y="-100" width="130" height="200" rx="12" fill="#ddd"/><rect x="-50" y="-82" width="100" height="55" fill="#66aaff"/><circle cx="-70" cy="70" r="15" fill="#111"/><circle cx="70" cy="70" r="15" fill="#111"/></g>`+scooter(440,235)+`<path d="M390 160Q500 160 500 260" stroke="#ffbf19" stroke-width="10" fill="none"/></g>`+end;
if(t==='zebra')return common+`<path d="M0 165H600"/><g fill="#fff">${[180,220,260,300,340,380].map(x=>`<rect x="${x}" y="115" width="22" height="100"/>`).join('')}</g></g>`+car(300,80,'#66aaff')+scooter(300,275)+end;
if(t==='bikeend')return common+`<path d="M180 0V250"/><path stroke-dasharray="16 14" d="M220 0V250"/></g><text x="155" y="75" fill="#fff" font-size="28">RADWEG</text><path d="M200 180V265" stroke="#ef4444" stroke-width="10"/>`+scooter(200,285)+car(410,220,'#66aaff')+end;
if(t==='blocked')return common+road+`<circle cx="250" cy="250" r="18" fill="#22c55e"/><circle cx="350" cy="250" r="18" fill="#22c55e"/>`+car(300,165,'#ef4444')+car(390,165,'#66aaff')+scooter(300,285)+end;
if(t==='ball')return common+`<path d="M0 245H600"/></g>`+car(160,170,'#777')+car(430,170,'#777')+`<circle cx="300" cy="210" r="20" fill="#fff" stroke="#111" stroke-width="5"/>`+scooter(300,290)+end;
if(t==='wetcurve')return common+`<path d="M80 330Q80 100 360 90Q520 85 600 20" stroke="#777" stroke-width="120"/><path d="M80 330Q80 100 360 90Q520 85 600 20" stroke="#fff" stroke-width="5" stroke-dasharray="20 20"/><text x="25" y="55" fill="#7dd3fc" font-size="42">💧 💧 💧</text></g>`+scooter(110,275,-15)+end;
if(t==='cross3')return common+road+scooter(300,275)+car(490,165,'#f4c430',90)+car(110,165,'#66aaff',90)+end;
if(t==='narrow')return common+`<path d="M0 165H600"/><path d="M250 0L285 330M350 0L315 330"/></g><g fill="#ff7a00"><rect x="260" y="120" width="25" height="45"/><rect x="315" y="175" width="25" height="45"/></g>`+scooter(150,230,90)+car(455,165,'#66aaff',90)+end;
if(t==='dog')return common+`<path d="M0 245H600"/></g><circle cx="430" cy="170" r="28" fill="#b8793d"/><circle cx="460" cy="150" r="15" fill="#b8793d"/><path d="M455 165L210 235" stroke="#eee" stroke-width="4"/>`+scooter(300,285)+end;
return common+road+scooter(300,275)+end}
const prevRender=window.renderQuiz;
window.renderQuiz=function(){prevRender();const it=session?.items?.[session.idx],m=it?.[4];if(!m?.visualV25)return;const card=document.querySelector('.card');if(!card||card.querySelector('.v25-scene'))return;const d=document.createElement('div');d.className='v25-scene';d.innerHTML=sceneSvg(m.scene);const qn=card.querySelector('.question');qn?.insertAdjacentElement('afterend',d)};
const st=document.createElement('style');st.textContent=`.v25-scene{margin:14px 0 22px;border:1px solid #3c4c69;border-radius:18px;overflow:hidden;background:#222}.v25-scene svg{display:block;width:100%;height:auto;max-height:310px}.v25-scene text{font-family:Arial,sans-serif;font-weight:700}`;document.head.appendChild(st);
})();