// V2.7 – automatische Aktualisierung je Version + mittiger großer Update-Knopf
(function(){
const VERSION='V2.7';
const SEEN_KEY='eroller_seen_version';
const BTN_KEY='eroller_update_button_'+VERSION;
const css=document.createElement('style');css.textContent=`@keyframes gudeFlyCenter{0%{transform:translate(-50%,-160px) scale(.65);opacity:0}70%{transform:translate(-50%,12px) scale(1.06);opacity:1}100%{transform:translate(-50%,0) scale(1);opacity:1}}.gude-fly{position:fixed;z-index:99998;left:50%;right:auto;top:22%;transform:translateX(-50%);width:min(86vw,560px);padding:24px 26px;border:4px solid #ffbf19;border-radius:26px;background:#111;color:#ffbf19;font-weight:1000;font-size:clamp(24px,5.5vw,38px);line-height:1.05;box-shadow:0 18px 60px #000;text-align:center;animation:gudeFlyCenter .9s ease-out both;cursor:pointer}.gude-fly small{display:block;margin-top:8px;color:#fff;font-size:.45em}.app-version-mark{text-align:center;margin:18px 0 92px;color:#777;font-size:11px;letter-spacing:.12em}.app-version-mark strong{color:#aaa}`;document.head.appendChild(css);
async function refreshApp(hideButton){if(hideButton)localStorage.setItem(BTN_KEY,'done');localStorage.setItem(SEEN_KEY,VERSION);try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(e){}location.replace(location.pathname+'?v=27&fresh='+Date.now()+'#home')}
async function autoRefresh(){if(localStorage.getItem(SEEN_KEY)===VERSION)return false;localStorage.setItem(SEEN_KEY,VERSION);await refreshApp(false);return true}
function flyButton(){if(localStorage.getItem(BTN_KEY)==='done')return;document.getElementById('gudeFly26')?.remove();const b=document.createElement('button');b.id='gudeFly26';b.className='gude-fly';b.innerHTML='Gude du Opfer 😎<small>App vollständig aktualisieren</small>';b.onclick=()=>refreshApp(true);document.body.appendChild(b)}
function versionFooter(){if((location.hash.slice(1)||'home')!=='home')return;const host=document.querySelector('.mh')||document.getElementById('app');if(!host)return;document.getElementById('appVersionMark')?.remove();const d=document.createElement('div');d.id='appVersionMark';d.className='app-version-mark';d.innerHTML=`BOLLER'S E-ROLLER FAHRSCHULE · <strong>${VERSION}</strong>`;host.appendChild(d)}
const oldHome=window.home;if(typeof oldHome==='function')window.home=function(){oldHome();setTimeout(versionFooter,0)};
(async()=>{const r=await autoRefresh();if(r)return;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{flyButton();setTimeout(versionFooter,50)});else{flyButton();setTimeout(versionFooter,50)}})();
})();