// V2.8 – deutlich größerer/schwererer Fragenpool + Prüfungszähler ohne 20er-Deckel
(function(){
const hard=[
["Du fährst 20 km/h. Ein Auto vor dir bremst plötzlich. Welche Aussage ist richtig?",["Bei 20 km/h brauche ich kaum Abstand","Reaktionsweg entsteht schon bevor ich überhaupt bremse","Nur der Bremsweg zählt"],1,"Der Anhalteweg besteht aus Reaktionsweg und Bremsweg."],
["Du näherst dich einer schlecht einsehbaren Kreuzung ohne Beschilderung. Was ist richtig?",["So fahren, dass du nötigenfalls rechtzeitig anhalten kannst","20 km/h sind immer zulässig","Klingeln ersetzt langsames Heranfahren"],0,"An unübersichtlichen Stellen musst du deine Geschwindigkeit der Sicht anpassen."],
["Ein Pkw blinkt rechts, fährt aber zunächst gerade weiter. Worauf darfst du dich verlassen?",["Auf den Blinker","Erst auf die tatsächliche Fahrbewegung und eine sichere Situation","Darauf, dass er dich gesehen hat"],1,"Blinkzeichen allein garantiert nicht, dass das Fahrzeug tatsächlich abbiegt oder dich gesehen hat."],
["Du willst an parkenden Autos vorbeifahren. Gleichzeitig kommt Gegenverkehr. Was ist entscheidend?",["Ob ausreichend Seitenraum für alle vorhanden ist","E-Roller dürfen immer zuerst","Der Gegenverkehr muss grundsätzlich warten"],0,"Bei Engstellen darf niemand gefährdet werden; nötigenfalls musst du warten."],
["Du fährst bei Dämmerung. Warum ist dunkle Kleidung zusätzlich problematisch?",["Andere erkennen dich später","Der Akku wird schneller leer","Die Bremsen werden schwächer"],0,"Sichtbarkeit beeinflusst, wie früh andere reagieren können."],
["Du bemerkst hinter dir ein schnell herannahendes Fahrzeug, während du einem Schlagloch ausweichen möchtest. Was zuerst?",["Sofort ausweichen","Rückwärtigen/seitlichen Verkehr prüfen und nur sicher ausweichen","Mitten auf der Straße anhalten"],1,"Ein Ausweichmanöver darf nicht unkontrolliert erfolgen."],
["Ein Fußgänger schaut auf sein Handy und läuft auf den Radweg zu. Was ist richtig?",["Auf deinem Vorrang bestehen","Tempo reduzieren, bremsbereit sein und mit einem Schritt auf den Radweg rechnen","Nur klingeln und Tempo halten"],1,"Erkennbare Unaufmerksamkeit verlangt zusätzliche Vorsicht."],
["Warum kann eine Vollbremsung auf nassem Laub besonders kritisch sein?",["Die Haftung kann stark reduziert sein","Laub erhöht die Geschwindigkeit","Die Beleuchtung fällt aus"],0,"Nasses Laub kann sehr rutschig sein."],
["Du fährst bergab in eine enge Kurve. Wann sollte die Geschwindigkeit angepasst werden?",["Vor der Kurve","Erst am Kurvenausgang","Mitten in der Kurve durch starkes Bremsen"],0,"Geschwindigkeit möglichst vor der Kurve reduzieren."],
["An einer Kreuzung hast du Vorfahrt. Ein Fahrzeug rollt trotzdem weiter in deine Fahrbahn. Was tust du?",["Beschleunigen, um zuerst durchzukommen","Bremsbereit sein und nötigenfalls verzichten","Hupen bzw. klingeln und unverändert weiter"],1,"Unfallvermeidung geht vor dem Bestehen auf Vorfahrt."],
["Warum ist der Bereich unmittelbar rechts neben einem Lkw besonders gefährlich?",["Der Fahrer kann dich trotz Spiegeln übersehen","Dort ist der Asphalt weicher","Lkw dürfen dort rückwärts fahren"],0,"Tote Winkel und der Abbiegeverlauf großer Fahrzeuge sind gefährlich."],
["Du möchtest links abbiegen und musst dabei eine Fahrspur queren. Was reicht NICHT aus?",["Nur ein Handzeichen","Verkehrsbeobachtung plus Handzeichen","Schulterblick und sicheres Einordnen"],0,"Ein Handzeichen allein gibt dir keinen Vorrang und ersetzt keine Verkehrsbeobachtung."],
["Du siehst eine grüne Ampel, aber direkt dahinter steht ein Stau. Wann darfst du einfahren?",["Immer bei Grün","Nur wenn du die Kreuzung voraussichtlich wieder räumen kannst","Wenn du klingelst"],1,"Eine Kreuzung darf auch bei Grün nicht blockiert werden."],
["Auf einer feuchten Metallplatte in einer Baustelle solltest du…",["möglichst ruhig und gerade fahren und starke Lenk-/Bremsmanöver vermeiden","stark beschleunigen","möglichst schräg mit starkem Lenkeinschlag fahren"],0,"Nasses Metall kann sehr glatt sein."],
["Du fährst an einer Reihe parkender Fahrzeuge vorbei. Bei einem Auto leuchten plötzlich die Rückfahrscheinwerfer. Was erwartest du?",["Das Auto könnte ausparken","Das Auto hat sicher Vorrang","Nichts Besonderes"],0,"Rückfahrscheinwerfer sind ein deutlicher Hinweis auf ein mögliches Ausparkmanöver."],
["Welche Kombination erhöht deinen Anhalteweg am stärksten?",["Nässe plus höhere Geschwindigkeit plus späte Reaktion","Trockene Straße plus niedrige Geschwindigkeit","Helles Tageslicht"],0,"Mehr Geschwindigkeit, weniger Haftung und verzögerte Reaktion verschlechtern die Anhaltemöglichkeit."],
["Du fährst an einer Bushaltestelle vorbei. Der Bus verdeckt deine Sicht. Was ist richtig?",["Mit plötzlich hervortretenden Personen rechnen","Schnell vorbei, bevor jemand kommt","Nur auf Autos achten"],0,"Verdeckte Sichtbereiche sind typische Gefahrenstellen."],
["Ein anderer Verkehrsteilnehmer winkt dich durch, obwohl die Verkehrslage unklar ist. Was gilt?",["Das Winken garantiert freie Fahrt","Du musst dich trotzdem selbst vergewissern, dass es sicher ist","Du musst sofort fahren"],1,"Du bleibst für deine sichere Fahrentscheidung verantwortlich."],
["Warum ist dichtes Auffahren hinter einem Transporter besonders ungünstig?",["Du hast weniger Sicht nach vorn und weniger Reaktionsraum","Der Roller verbraucht mehr Strom","Der Transporter könnte schneller werden"],0,"Sicht und Sicherheitsabstand sind eingeschränkt."],
["Du willst über Straßenbahnschienen fahren. Welche Linie ist meist sicherer?",["Möglichst mit ausreichend großem Winkel queren","Möglichst lange parallel in der Rille fahren","Auf der Schiene stark bremsen"],0,"Kleine Räder können sich bei flachem Winkel leichter in Schienen verkanten."],
["Ein Auto überholt dich sehr knapp. Was ist die sinnvollste Reaktion?",["Ruhig Spur halten, Geschwindigkeit kontrollieren und nicht erschreckt ausweichen","Sofort nach links ziehen","Dem Auto hinterherfahren"],0,"Hektische Ausweichbewegungen können die Gefahr vergrößern."],
["Bei starkem Seitenwind verlässt du den Schutz einer Häuserzeile. Womit musst du rechnen?",["Mit einem plötzlichen seitlichen Windstoß","Mit automatisch besserer Haftung","Mit kürzerem Bremsweg"],0,"Wind kann an offenen Stellen plötzlich stärker wirken."],
["Vor dir fährt ein Kind auf dem Fahrrad und schaut mehrfach nach hinten. Was ist sinnvoll?",["Abstand vergrößern und mit einem Richtungswechsel rechnen","Sofort knapp überholen","Dicht auffahren, damit es gerade fährt"],0,"Das Verhalten deutet auf Unsicherheit oder einen bevorstehenden Richtungswechsel hin."],
["Du kommst aus einem verkehrsberuhigten Bereich auf eine normale Straße. Was gilt beim Einfahren?",["Besondere Vorsicht; andere Verkehrsteilnehmer dürfen nicht gefährdet werden","Du hast automatisch Vorfahrt","Rechts vor links gibt dir immer Vorrang"],0,"Beim Ausfahren aus einem verkehrsberuhigten Bereich ist besondere Vorsicht erforderlich."],
["Warum kann eine Pfütze selbst ohne Aquaplaning gefährlich sein?",["Sie kann ein Schlagloch verdecken","Wasser hebt die Vorfahrt auf","Sie macht den Roller automatisch schneller"],0,"Unter Wasser können Unebenheiten oder tiefe Löcher verborgen sein."],
["Du bemerkst, dass deine Sicht durch Regen auf der Brille stark eingeschränkt ist. Was ist richtig?",["Tempo an die tatsächliche Sicht anpassen und nötigenfalls anhalten","Mit 20 km/h weiter, weil das erlaubt ist","Nur dichter hinter einem Auto fahren"],0,"Du darfst nur so schnell fahren, wie du die Situation sicher überblicken kannst."],
["Du fährst an einer Einmündung vorbei. Ein Autofahrer schaut nur in die andere Richtung. Was bedeutet das für dich?",["Damit rechnen, dass er dich nicht gesehen hat","Er muss dich gesehen haben","Schneller vorbeifahren"],0,"Fehlender Blickkontakt ist ein Warnsignal."],
["Beim Bremsen blockiert bzw. rutscht ein Rad auf losem Untergrund. Was ist wichtig?",["Lenkung möglichst kontrolliert halten und Fahrweise vorher an den Untergrund anpassen","Noch ruckartiger bremsen","Lenker abrupt herumreißen"],0,"Abrupte Manöver verschärfen auf losem Untergrund die Instabilität."],
["Du willst zwischen zwei wartenden Fahrzeugkolonnen hindurchfahren. Warum ist das riskant?",["Andere können Lücken kreuzen und dich spät sehen","Weil der Akku dort keinen Empfang hat","Es ist nur bei Regen riskant"],0,"In Fahrzeuglücken können plötzlich Abbieger oder Fußgänger auftauchen."],
["Welche Aussage zur eigenen Vorfahrt ist am sichersten?",["Vorfahrt bedeutet, dass ich nie bremsen muss","Auch mit Vorfahrt muss ich erkennbare Gefahren berücksichtigen","Vorfahrt gilt nur für Autos"],1,"Verkehrsregeln entbinden nicht von der Pflicht, Unfälle zu vermeiden."],
["Du siehst hinter einer Kurve nur 15 Meter weit. Welche Geschwindigkeit ist richtig?",["Eine, bei der du innerhalb des übersehbaren Bereichs sicher reagieren und anhalten kannst","Immer exakt 20 km/h","Mindestens 15 km/h"],0,"Die Geschwindigkeit muss zur Sichtweite passen."],
["Ein Fahrzeug hält ungewöhnlich weit vor einer Kreuzung. Was könnte das bedeuten?",["Es kann jemandem die Vorfahrt lassen oder eine Gefahr verdecken","Es bedeutet sicher freie Fahrt für dich","Es ist immer eine Panne"],0,"Ungewöhnliches Verhalten anderer sollte dich aufmerksam machen."],
["Warum sollte man bei unbekannter Strecke nicht direkt am Geschwindigkeitslimit fahren?",["Weil unerwartete Unebenheiten oder Verkehrsführungen auftreten können","Weil 20 km/h nur auf bekannten Strecken erlaubt sind","Weil der Akku sonst verboten heiß wird"],0,"Unbekannte Situationen verlangen zusätzliche Reserve."],
["Du fährst nachts aus einem hell beleuchteten Bereich in eine dunkle Straße. Was kann passieren?",["Deine Augen brauchen kurz zur Anpassung; Tempo reduzieren","Deine Bremsen brauchen Anpassungszeit","Die Vorfahrt ändert sich"],0,"Die Dunkeladaptation ist nicht augenblicklich."],
["Eine Person öffnet auf der Beifahrerseite eines parkenden Autos die Tür zum Radweg. Welche Vorsorge hilft vorher?",["Ausreichender seitlicher Abstand und angepasste Geschwindigkeit","Dicht an den Autos fahren","Nur klingeln"],0,"Dooring-Gefahr lässt sich durch Abstand und Bremsbereitschaft reduzieren."],
["Du hörst ein Einsatzfahrzeug, aber die Richtung ist unklar. Was ist falsch?",["Aufmerksam werden und Umgebung prüfen","Unverändert mit Kopfhörern weiterfahren","Bereit sein, freie Bahn zu schaffen"],1,"Warnsignale dürfen nicht ignoriert werden."],
["Eine Ampel ist ausgefallen, aber Vorfahrtsschilder sind vorhanden. Was orientiert dich?",["Die vorhandene Beschilderung und allgemeine Vorfahrtregeln","Wer zuerst hupt","E-Roller haben immer Nachrang"],0,"Bei ausgefallener Lichtzeichenanlage gelten die vorhandenen Verkehrszeichen bzw. allgemeinen Regeln."],
["Du willst jemanden überholen, dessen Fahrweise schwankt. Wann solltest du es lassen?",["Wenn kein ausreichender Seitenabstand und keine klare Situation vorhanden sind","Nur nachts","Nie – E-Roller müssen immer überholen"],0,"Überholen darf nur erfolgen, wenn es sicher möglich ist."],
["Was ist bei einer Gefahrenbremsung besonders wichtig?",["Das Fahrzeug möglichst kontrolliert halten und nicht gleichzeitig hektisch ausweichen","Augen schließen","Lenker loslassen"],0,"Kontrolle und Stabilität sind bei starkem Bremsen entscheidend."],
["Warum kann Müdigkeit ähnlich gefährlich sein wie Ablenkung?",["Reaktion, Wahrnehmung und Entscheidungen werden schlechter","Nur der Akkuverbrauch steigt","Sie betrifft nur Autofahrer"],0,"Müdigkeit verschlechtert zentrale Fähigkeiten für die sichere Verkehrsteilnahme."]
];
if(typeof q!=='undefined'&&!q.some(x=>x[4]?.hardV28))hard.forEach(x=>{x[4]={hardV28:true};q.push(x)});

// Gesamte lokale Prüfungshistorie behalten; kein 20er-Limit.
if(typeof store!=='undefined')store.add=function(x){const a=this.get();a.unshift(x);localStorage.setItem('eroller_history',JSON.stringify(a.slice(0,5000)))};

// Readiness-Historie ebenfalls deutlich erweitern.
const READY='eroller_readiness_v24';
function patchReadiness(){try{const r=JSON.parse(localStorage.getItem(READY)||'{"practice":[],"exams":[]}');if(!Array.isArray(r.exams))r.exams=[];if(!Array.isArray(r.practice))r.practice=[];localStorage.setItem(READY,JSON.stringify(r))}catch(e){}}
patchReadiness();

// Startseite: echten Gesamtzähler aus allen gespeicherten Prüfungen anzeigen.
function addExamCounter(){if((location.hash.slice(1)||'home')!=='home')return;const host=document.querySelector('.mh')||document.getElementById('app');if(!host)return;document.getElementById('examTotalV28')?.remove();const hist=(typeof store!=='undefined'?store.get():[]);const exams=hist.filter(x=>String(x.type||'').toLowerCase().includes('prüfung')||String(x.type||'').toLowerCase().includes('pruefung'));const passed=exams.filter(x=>x.passed).length;const d=document.createElement('div');d.id='examTotalV28';d.className='exam-total-v28';d.innerHTML=`<strong>🏁 Prüfungen bestanden: ${passed}</strong><span>von ${exams.length} absolvierten Prüfungen auf diesem Gerät</span>`;const target=document.getElementById('readinessBox')||document.querySelector('.mh-stats');(target||host.firstElementChild)?.insertAdjacentElement('afterend',d)}
const st=document.createElement('style');st.textContent='.exam-total-v28{margin:12px 0;padding:13px 15px;border:1px solid #3c4c69;border-radius:14px;background:#151b27;display:flex;justify-content:space-between;gap:10px;align-items:center}.exam-total-v28 span{font-size:12px;color:#9ca3af;text-align:right}@media(max-width:520px){.exam-total-v28{align-items:flex-start;flex-direction:column}.exam-total-v28 span{text-align:left}}';document.head.appendChild(st);
const ph=window.home;if(typeof ph==='function')window.home=function(){ph();setTimeout(addExamCounter,30)};window.addEventListener('hashchange',()=>setTimeout(addExamCounter,50));setTimeout(addExamCounter,100);
})();